[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p logs"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT" 