[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
context = "."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { 
  ENVIRONMENT = "production",
  DB_ECHO = "false",
  WEBHOOK_MONITORING_ENABLED = "true"
}

[environments.staging]
variables = { 
  ENVIRONMENT = "staging",
  DB_ECHO = "true",
  WEBHOOK_MONITORING_ENABLED = "true"
} 