"""add_audio_data_b64_to_text_segment

Revision ID: 117af58c89f8
Revises: 9f70f2e17485
Create Date: 2025-05-14 23:24:45.178626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117af58c89f8'
down_revision: Union[str, None] = '9f70f2e17485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_segments', sa.Column('audio_data_b64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_segments', 'audio_data_b64')
    # ### end Alembic commands ###
