"""add_word_timestamps_to_texts

Revision ID: 17a18c0dd741
Revises: 4484d5d5609b
Create Date: 2025-06-10 16:25:15.436436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a18c0dd741'
down_revision: Union[str, None] = '4484d5d5609b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('word_timestamps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'word_timestamps')
    # ### end Alembic commands ###
