"""make sound_effects audio_data_b64 nullable

Revision ID: 2c9cd064a035
Revises: 9b2b768fdadd
Create Date: 2025-07-01 17:52:50.770377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9cd064a035'
down_revision: Union[str, None] = '9b2b768fdadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
