"""add_force_alignment_timestamp_to_texts

Revision ID: 4484d5d5609b
Revises: 0551871fb543
Create Date: 2025-06-10 14:14:35.150455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4484d5d5609b'
down_revision: Union[str, None] = '0551871fb543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('force_alignment_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'force_alignment_timestamp')
    # ### end Alembic commands ###
