"""drop_sound_effect_cache_table

Revision ID: 82874e620bcc
Revises: 17a18c0dd741
Create Date: 2025-06-10 19:25:58.581722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82874e620bcc'
down_revision: Union[str, None] = '17a18c0dd741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sound_effect_cache_effect_keyword', table_name='sound_effect_cache')
    op.drop_table('sound_effect_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_effect_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('effect_keyword', sa.VARCHAR(), nullable=False),
    sa.Column('prompt_used', sa.TEXT(), nullable=False),
    sa.Column('audio_data_b64', sa.TEXT(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sound_effect_cache_effect_keyword', 'sound_effect_cache', ['effect_keyword'], unique=False)
    # ### end Alembic commands ###
