"""Initial migration

Revision ID: aaada83994fa
Revises: 
Create Date: 2025-05-05 00:13:27.564405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaada83994fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'texts',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('analyzed', sa.Boolean(), nullable=False)
    )
    op.create_table(
        'characters',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('text_id', sa.UUID(as_uuid=True), sa.ForeignKey('texts.id'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('provider_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_table(
        'text_segments',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('text_id', sa.UUID(as_uuid=True), sa.ForeignKey('texts.id'), nullable=False),
        sa.Column('character_id', sa.UUID(as_uuid=True), sa.ForeignKey('characters.id'), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('audio_file', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_table(
        'process_logs',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True),
        sa.Column('text_id', sa.UUID(as_uuid=True), sa.ForeignKey('texts.id'), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('operation', sa.String(), nullable=False),
        sa.Column('request', sa.JSON(), nullable=True),
        sa.Column('response', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_logs')
    op.drop_table('text_segments')
    op.drop_table('characters')
    op.drop_table('texts')
    # ### end Alembic commands ###
