"""make sound_effects audio_data_b64 nullable_fixed

Revision ID: db60ed29efff
Revises: 2c9cd064a035
Create Date: 2025-07-01 17:54:51.095869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db60ed29efff'
down_revision: Union[str, None] = '2c9cd064a035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite doesn't support ALTER COLUMN, so we need to recreate the table
    op.execute("""
        CREATE TABLE sound_effects_new (
            effect_id INTEGER NOT NULL,
            effect_name VARCHAR NOT NULL,
            text_id INTEGER NOT NULL,
            segment_id INTEGER,
            start_word VARCHAR NOT NULL,
            end_word VARCHAR NOT NULL,
            start_word_position INTEGER,
            end_word_position INTEGER,
            prompt TEXT NOT NULL,
            audio_data_b64 TEXT,
            start_time FLOAT,
            end_time FLOAT,
            total_time INTEGER,
            rank INTEGER,
            created_at DATETIME DEFAULT (CURRENT_TIMESTAMP),
            audio_timestamp DATETIME,
            PRIMARY KEY (effect_id),
            FOREIGN KEY(text_id) REFERENCES texts (id),
            FOREIGN KEY(segment_id) REFERENCES text_segments (id)
        )
    """)
    
    # Copy data from old table
    op.execute("""
        INSERT INTO sound_effects_new 
        SELECT effect_id, effect_name, text_id, segment_id, start_word, end_word, 
               start_word_position, end_word_position, prompt, audio_data_b64, 
               start_time, end_time, total_time, rank, created_at, audio_timestamp
        FROM sound_effects
    """)
    
    # Drop old table and rename new table using SQL
    op.execute('DROP TABLE sound_effects')
    op.execute('ALTER TABLE sound_effects_new RENAME TO sound_effects')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sound_effects', 'audio_data_b64',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
